import FWCore.ParameterSet.Config as cms

## 2015 + new phase 1 pixel detector + Tracker BarrelEndcapv(described as a pixel detector before the detid migration)

XMLIdealGeometryESSource = cms.ESSource("XMLIdealGeometryESSource",
    geomXMLFiles = cms.vstring('Geometry/CMSCommonData/data/materials.xml',
        'Geometry/CMSCommonData/data/rotations.xml',
        'Geometry/CMSCommonData/data/extend/cmsextent.xml',
        'Geometry/CMSCommonData/data/PhaseI/cms.xml',
        'Geometry/CMSCommonData/data/cmsMother.xml',
        'Geometry/CMSCommonData/data/cmsTracker.xml',
        #'Geometry/CMSCommonData/data/caloBase.xml',
        #'Geometry/CMSCommonData/data/cmsCalo.xml',
        #'Geometry/CMSCommonData/data/muonBase.xml',
        #'Geometry/CMSCommonData/data/cmsMuon.xml',
        'Geometry/CMSCommonData/data/mgnt.xml',
        'Geometry/CMSCommonData/data/PhaseI/beampipe.xml',
        'Geometry/CMSCommonData/data/cmsBeam.xml',
        #'Geometry/CMSCommonData/data/muonMB.xml',
        #'Geometry/CMSCommonData/data/muonMagnet.xml',
        'Geometry/CMSCommonData/data/cavern.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdMaterials.xml',
        'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdCylinder.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwd.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdDisks.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk1.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk2.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk3.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk4.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk5.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk6.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk7.xml',
# 'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk8.xml',
# 'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk9.xml',
# 'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdInnerDisk10.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk1.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk2.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk3.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk4.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk5.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk6.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk7.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk8.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk9.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdOuterDisk10.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade1.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade2.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade3.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade4.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade5.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade6.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade7.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade8.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade9.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/pixfwdblade10.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarmaterial.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladder.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladderfull0.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladderfull1.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladderfull2.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladderfull3.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer0.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer1.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer2.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer3.xml',
        'Geometry/TrackerCommonData/data/PhaseII/BarrelEndcap5D/pixbar.xml',
        'Geometry/TrackerCommonData/data/trackermaterial.xml',
        'Geometry/TrackerCommonData/data/PhaseII/BarrelEndcap5D/tracker.xml',
        'Geometry/TrackerCommonData/data/trackerpixbar.xml',
        'Geometry/TrackerCommonData/data/PhaseI/trackerpixfwd.xml',
        'Geometry/TrackerCommonData/data/PhaseII/Pixel10D/trackerStructureTopology.xml',
        'Geometry/TrackerSimData/data/PhaseII/Pixel10D/trackersens.xml',
        'Geometry/TrackerRecoData/data/PhaseII/Pixel10D/trackerRecoMaterial.xml',
        'Geometry/TrackerSimData/data/PhaseII/Pixel10D/trackerProdCuts.xml',
        'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        'Geometry/CMSCommonData/data/FieldParameters.xml'),
    rootNodeName = cms.string('cms:OCMS')
)


